INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`) VALUES ('Placa de video GTX1660', 'Placa de video GTX1660', 'Placa de video GTX1660', 10000, '../images/GTX1660.jpg');
INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`)  VALUES ('Placa de video GTX1050', 'Placa de video GTX1050', 'Placa de video GTX 1050', 15000, '../images/GTX1050.jpg');
INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`) VALUES (Placa de video RTX3070, 'Placa de video RTX3070', 'Placa de video RTX3070', 20000, '../images/RTX3070.jpg');
INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`)  VALUES ('Placa de video RTX3070', 'Placa de video RTX3070', 'Placa de video RTX3080', 25000, '../images/RTX3080.jpg');
INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`)  VALUES ('Kit gamer 1', 'Kit gamer 1', 'Mouse, teclado, headset y pad gamer', 1500, '../images/kit-gamer-2.jpg');
INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`)  VALUES ('Kit gamer 2', 'Kit gamer 2', 'Gabinete, parlantes, mouse y teclado gamer', 2000, '../images/kit-gamer-2.jpg');
INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`)  VALUES ('Kit gamer 2', 'Kit gamer 3', 'Headset mouse y teclado', 2500, '../images/kit-gamer-3.jpg');
INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`)  VALUES ('Kit gamer 4', 'Kit gamer 4', 'Headset, teclado, mouse y pad gamer', 2500, '../images/kit-gamer-4.jpg');
INSERT INTO `productos`(`marca`,`producto` , `descripcion`, `precio`, `imagen`) VALUES ('PC armada 1', 'PC armada 1', 'PC gamer con monitor, teclado y mouse', 190000, '../images/pc-armada-1.jpg');
INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`)  VALUES ('PC armada 1', 'PC armada 2', 'PC gamer con monitor', 195000, '../images/pc-armada-2.jpg');
INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`)  VALUES ('PC armada 3', 'PC armada 3', ' PC gamer con monitor, teclado, mouse y headset', 198000, '../images/pc-armada-3.jpg');
INSERT INTO `productos`(`marca`,`producto` , `descripcion`, `precio`, `imagen`) VALUES ('PC armada 4', 'PC armada 4', 'PC gamer con monitor, teclado, mouse y parlantes', 199000, '../images/pc-armada-4.jpg');
INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`)  VALUES ('PC armada 5', 'PC armada 5', 'PC gamer con monitor, teclado, mouse y parlantes', 215000, '../images/pc-armada-4.jpg');
INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`) VALUES ('PC armada 6', 'PC armada 6', 'PC gamer con monitor, teclado, mouse y headset', 200000, '../images/pc-armada-3.jpg');
INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`)  VALUES ('PC armada 7', 'PC armada 7', 'PC gamer con monitor', 220000, '../images/pc-armada-2.jpg');
INSERT INTO `productos`(`marca`,`producto` , `descripcion`, `precio`, `imagen`)  VALUES ('PC armada 8', 'PC armada 8', 'PC gamer con monitor, teclado y mouse', 250000, '../images/pc-armada-1.jpg');
INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`)  VALUES ('Kit gamer 5', 'Kit gamer 5', 'Headset, teclado, mouse y pad gamer', 50000, '../images/kit-gamer-4.jpg');
INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`) VALUES ('Kit gamer 6', 'Kit gamer 6', 'Headset mouse y teclado', 25000, '../images/kit-gamer-3.jpg');
INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`)  VALUES ('Kit gamer 7', 'Kit gamer 7', 'gabinete, parlantes, mouse y teclado gamer', 15000, '../images/kit-gamer-2.jpg');
INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`)  VALUES ('Kit gamer 8', 'Kit gamer 8', 'mouse, teclado, headset y pad gamer', 9250, '../images/kit-gamer-1.jpg');
INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`)  VALUES ('Placa de video RTX3070', 'Placa de video RTX3070', 'Placa de video RTX3080', 350000, '../images/RTX3080.jpg');
INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`)  VALUES ('Placa de video RTX3070', 'Placa de video RTX3070', 'Placa de video RTX3070', 210000, '../images/RTX3070.jpg');
INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`)  VALUES ('Placa de video GTX1050', 'Placa de video GTX1050', 'Placa de video GTX 1050', 95000, '../images/GTX1050.jpg');
INSERT INTO `productos` (`marca`,`producto` , `descripcion`, `precio`, `imagen`)  VALUES ('Placa de video GTX1660', 'Placa de video GTX1660', 'Placa de video GTX1660', 95390, '../images/GTX1660.jpg');
